name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.1

      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm run build

      - name: Upload build output as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/

  deploy:
    needs: build

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy the build output to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
